FROM rocker/r-ver:4.1.3
RUN apt-get update && apt-get install -y  cmake git-core libcurl4-openssl-dev libgit2-dev libglpk-dev libgmp-dev libicu-dev libpng-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev libfreetype6-dev && rm -rf /var/lib/apt/lists/*
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.4.0")'
RUN Rscript -e 'remotes::install_version("png",upgrade="never", version = "0.1-7")'
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.38")'
RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.5.2")'
RUN Rscript -e 'remotes::install_version("ggplot2",upgrade="never", version = "3.3.5")'
RUN Rscript -e 'remotes::install_version("tidyselect",upgrade="never", version = "1.1.2")'
RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.8")'
RUN Rscript -e 'remotes::install_version("tidyr",upgrade="never", version = "1.2.0")'
RUN Rscript -e 'remotes::install_version("flashClust",upgrade="never", version = "1.01-2")'
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.22")'
RUN Rscript -e 'remotes::install_version("dynamicTreeCut",upgrade="never", version = "1.63-1")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.7.1")'
RUN Rscript -e 'remotes::install_version("DBI",upgrade="never", version = "1.1.2")'
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3.1")'
RUN Rscript -e 'remotes::install_version("reshape2",upgrade="never", version = "1.4.4")'
RUN Rscript -e 'remotes::install_version("dendextend",upgrade="never", version = "1.15.2")'
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.13")'
RUN Rscript -e 'remotes::install_version("BiocManager", upgrade="never", version = "1.30.16")'
RUN Rscript -e 'BiocManager::install("impute")'
RUN Rscript -e 'BiocManager::install("preprocessCore")'
RUN Rscript -e 'BiocManager::install("GO.db")'
#RUN Rscript -e 'BiocManager::install("AnnotationDbi")'
#RUN Rscript -e ''
RUN Rscript -e 'remotes::install_version("WGCNA",upgrade="never", version = "1.70-3", dependencies = TRUE)'
RUN Rscript -e 'remotes::install_version("visNetwork",upgrade="never", version = "2.1.0")'
RUN Rscript -e 'BiocManager::install("SummarizedExperiment")'
RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "2.1.0")'
RUN Rscript -e 'remotes::install_version("shinybusy",upgrade="never", version = "0.3.0")'
RUN Rscript -e 'BiocManager::install("runibic")'
RUN Rscript -e 'remotes::install_version("RSQLite",upgrade="never", version = "2.2.12")'
RUN Rscript -e 'BiocManager::install("ReactomePA")'
RUN Rscript -e 'BiocManager::install("QUBIC")'
RUN Rscript -e 'BiocManager::install("PREDAsampledata")'
RUN Rscript -e 'BiocManager::install("PREDA")'
RUN Rscript -e 'remotes::install_version("plotly",upgrade="never", version = "4.10.0")'
RUN Rscript -e 'BiocManager::install("PGSEA")'
RUN Rscript -e 'BiocManager::install("pathview")'
RUN Rscript -e 'remotes::install_version("loose.rock",upgrade="never", version = "1.2.0")'
RUN Rscript -e 'BiocManager::install("limma")'
RUN Rscript -e 'BiocManager::install("KEGGREST")'
RUN Rscript -e 'BiocManager::install("InteractiveComplexHeatmap")'
RUN Rscript -e 'remotes::install_version("igraph",upgrade="never", version = "1.3.0")'
RUN Rscript -e 'remotes::install_version("gplots",upgrade="never", version = "3.1.1")'
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.3.2")'
RUN Rscript -e 'remotes::install_version("GetoptLong",upgrade="never", version = "1.0.5")'
RUN Rscript -e 'BiocManager::install("gage")'
RUN Rscript -e 'BiocManager::install("fgsea")'
RUN Rscript -e 'remotes::install_version("factoextra",upgrade="never", version = "1.0.7")'
RUN Rscript -e 'BiocManager::install("edgeR")'
RUN Rscript -e 'remotes::install_version("e1071",upgrade="never", version = "1.7-9")'
RUN Rscript -e 'BiocManager::install("DESeq2")'
RUN Rscript -e 'BiocManager::install("ComplexHeatmap")'
RUN Rscript -e 'remotes::install_version("circlize",upgrade="never", version = "0.4.14")'
RUN Rscript -e 'BiocManager::install("BiocGenerics")'
RUN Rscript -e 'BiocManager::install("Biobase")'
RUN Rscript -e 'remotes::install_version("biclust",upgrade="never", version = "2.0.3")'
RUN apt-get update && apt-get install -y libfontconfig1-dev && rm -rf /var/lib/apt/lists/*
RUN Rscript -e 'remotes::install_version("systemfonts", upgrade = "never", version = "1.0.4")'
RUN Rscript -e 'BiocManager::install("annaffy")'
RUN Rscript -e 'install.packages("http://www.bioconductor.org/packages//2.11/data/annotation/src/contrib/KEGG.db_2.8.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/3.10/bioc/src/contrib/PGSEA_1.60.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'remotes::install_version("svglite", upgrade = "never", version = "2.1.0")'
RUN Rscript -e 'remotes::install_version("kableExtra", upgrade = "never", version = "1.3.4")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/ComplexHeatmap_2.12.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/InteractiveComplexHeatmap_1.4.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'remotes::install_version("dqrng", upgrade = "never", version = "0.3.0")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/sparseMatrixStats_1.8.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/DelayedMatrixStats_1.18.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/beachmat_2.12.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/ScaledMatrix_1.4.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'remotes::install_version("irlba", upgrade = "never", version = "2.3.5")'
RUN Rscript -e 'remotes::install_version("rsvd", upgrade = "never", version = "1.0.5")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/BiocSingular_1.12.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'install.packages("https://bioconductor.org/packages/release/bioc/src/contrib/PCAtools_2.8.0.tar.gz", repos=NULL, type="source")'
RUN Rscript -e 'remotes::install_version("Rtsne", upgrade = "never", version = "0.16")'
RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
RUN rm -rf /build_zone
EXPOSE 3838
CMD R -e "options('shiny.port'=3838,shiny.host='0.0.0.0');idepGolem::run_app()"
